% startupadigator: will add adigator directories to the Matlab path.
% Copyright 2011-2014 Matthew J. Weinstein and Anil V. Rao
% Copyright 2025-2026 GMV / Pedro Lourenço (embedded fork additions)
% Distributed under the GNU General Public License version 3.0
currpath = pwd;
addpath(currpath);
addpath([currpath,filesep,'lib']);
addpath([currpath,filesep,'lib',filesep,'cadaUtils']);
addpath([currpath,filesep,'util']);
addpath([currpath,filesep,'embedding']);

fprintf('     ADiGator Successfully Installed\n\n')

copyingfile = [currpath,filesep,'LICENSE'];
if strcmp(filesep,'\');copyingfile = regexprep(copyingfile,'\\','\\\\'); end
COPYINGlink = ['<a href="matlab: opentoline(''',copyingfile,''',1)">LICENSE</a>'];
COPYINGurl  = '<a href="http://www.gnu.org/licenses/">http://www.gnu.org/licenses/</a>';

fprintf([...
'     ADiGator is free software: you can redistribute it and/or modify\n',...
'     it under the terms of the GNU General Public License as published by\n',...
'     the Free Software Foundation, either version 3 of the License, or\n',...
'     (at your option) any later version.\n',...
' \n',...
'     ADiGator is distributed in the hope that it will be useful,\n',...
'     but WITHOUT ANY WARRANTY; without even the implied warranty of\n',...
'     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n',...
'     GNU General Public License for more details.\n',...
' \n',...
'     You should have received a copy of the GNU General Public License\n',...
'     along with ADiGator at ',COPYINGlink,'.\n',...  
'     If not, see ',COPYINGurl,'.\n\n']);

adigatorurl = '<a href="https://github.com/pdlourenco/adigator-embedded">https://github.com/pdlourenco/adigator-embedded</a>';

fprintf([...
'     For updated versions of the code please visit the fork repository\n',...
'     at ',adigatorurl,'.\n     Please report any issues to the GitHub issue tracker.\n']);