function info = adigatorGenDerFile_embedded(DerType,UserFunName,UserFunInputs,varargin)
%ADIGATORGENDERFILE_EMBEDDED    This function generates embeddable files with
%                               implementing the selected derivatives of 
%                               the user provided UserFunName
%
% ADiGator Derivative File Generation Function: this function is used when you
% wish to generate a Hessian, gradient, or Jacobian of a function with an input variable
% of differentiation (and any auxiliary inputs), and a single output. This
% simply calls the function adigator twice and creates a wrapper function
% s.t. the input of the resulting file is the same as the input to the
% original user function, but outputs the Hessian, gradient, Jacobian, and 
% function values as requested.
%
% "Vanilla" ADiGator files use global variables and load .mat files in runtime
% which is not acceptable in embedded code. This file patches the vanilla
% files in one of two ways:
%       'c'lassic:      no patching is performed. 3 files are generated by
%                       each derivative (the main wrapper file, the .mat file
%                       containing the static indexing information, and the
%                       actual derivative file implementing ADiGator's 
%                       process.
%       coder'l'oad:    global variables are replaced by persistent variables
%                       the runtime load is replaced by a compile-time load
%                       and the values are set as constants. 2 files are
%                       generated: 1 m-file and 1 mat-file.
%       'i'nline:       no global or persistent variables are used, as well
%                       as loading. All the required information is within
%                       the generated Jacobian, Hessian, gradient file.
%
%   Input:
%       DerType         'jacobian', 'hessian', 'gradient', or
%                       'gradient-reverse' indicates the chosen derivative.
%                       'gradient-reverse' produces a REVERSE-mode (adjoint)
%                       gradient <fn>_RGrd via adigatorGenRevGradFile, embedded
%                       through the same c/l/i pipeline (roadmap R16, issue
%                       #73); it requires a scalar cost and unrolled code, and
%                       its file is self-contained (one file, no separate
%                       wrapper) - fully vectorized adjoints carry no static
%                       data at all (ANALYSIS §3.5).
%       UserFunName     name of the user function to be differentiated
%       UserFunInputs   cell with list of inputs to the function
%                       can include differentiating variables or auxiliary
%                       use the adigatorCreateDerivInput(size,varname) and
%                               adigatorCreateAuxInput(size) utilities
%       options         optional input with the possible ADiGator options
%                       please consult adigatorOptions. Defaults specific to
%                       this entry point (ADR-0012): an unset
%                       embed_mode defaults to 'i' (inline) and an unset
%                       slim_embed defaults to ON - calling this function
%                       implies the user wants embeddable, optimized code.
%                       Pass either option explicitly to override.
%
%   Output:
%       info            information about the differentiation process
%
%   Note: 'gradient' and 'hessian' modes both produce myfun_Grd /
%   myfun_ADiGatorGrd files. The files are functionally equivalent (same
%   first derivative, same column-gradient convention), so generating one
%   mode after the other harmlessly overwrites them.
%
%	Dependencies:
%		adigatorGenJacFile, adigatorGenHesFile, structure_to_embed_mfile, adigator_patch_derivative, prune_adigator_mat
%
%   Copyright GMV, S.A.
%   Property of GMV, S.A.; all rights reserved
%   2025-10  PEDRO LOURENÇO (PADL) - palourenco@gmv.com
%
%   Changelog:
%       2026-06    Extract the .mat pruner to prune_adigator_mat for
%                  testability (fixes B5) with integer down-casting
%                  restricted to Index* fields (B1) (PR #3).
%                  Print an explicit notice that a pruned .mat no longer
%                  supports re-differentiation (B6, PR #8).
%
%   TODO:
%       - Remove the computation of unnecessary variables by running CHECKCODE on each file.
%         Some functions load the mat file and assign Gator*Data structures but don't use them.
%         Each ADiGator derivative function returns the desired derivative as well as all 
%         lower order derivatives and the function itself. This might not be desirable in
%         embedded code, where only the minimum number of computations should take place

%% -------------------------- ARGUMENTS PARSING -------------------------%%
% parse options
opts = adigatorOptions();
userSetOverwrite = false;
if nargin>3
    optfields = fieldnames(varargin{1});
    for Fcount = 1:length(optfields)
        % v2.0 (B12 fix): lower-case only the destination field; the user's
        % struct must be read with the field name they actually used
        opts.(lower(optfields{Fcount})) = varargin{1}.(optfields{Fcount});
    end
    userSetOverwrite = any(strcmpi(optfields,'overwrite'));
end
% Embedded-generation defaults (ADR-0012): calling this entry point
% means the user wants embeddable, optimized output, so an UNSET ([]) embed_mode
% and slim_embed default to inline + slim here (the other generators resolve []
% to classic / off). Any value the user actually set is honoured.
if isempty(opts.embed_mode); opts.embed_mode = 'i';  end
if isempty(opts.slim_embed); opts.slim_embed = true; end
% OVERWRITE default: like the other wrapper-generation entry points, this one
% regenerates by default (adigatorOptions NOTES: the OVERWRITE default differs
% for the wrapper generators vs. the basic adigator file). The inner wrappers
% force overwrite=1 only when the caller passes NO overwrite field; but below we
% forward a fully-resolved opts that always carries an overwrite value, which
% would otherwise suppress that. Restore the documented default here unless the
% caller set overwrite explicitly, so regenerating over stale files still works.
if ~userSetOverwrite; opts.overwrite = 1; end
opts.embed_mode = adigatorNormalizeEmbedMode(opts.embed_mode); % v2.0 (B11 fix)
% Forward the fully-resolved options to the inner generators so the wrapper and
% the post-processing agree on the mode (previously the caller's raw struct was
% forwarded, which could disagree with the resolved opts).
varargin = {opts};

%% --------------------- Call the ADiGator wrappers ---------------------%%
switch DerType
    case 'jacobian'
        info = adigatorGenJacFile(UserFunName,UserFunInputs,varargin{:});
    case 'hessian'
        info = adigatorGenHesFile(UserFunName,UserFunInputs,varargin{:});
    case 'gradient'
        info = adigatorGenJacFile(UserFunName,UserFunInputs,varargin{:},'Grd');
    case 'gradient-reverse'
        % R16b (issue #73): reverse-mode gradient through the embed pipeline.
        % adigatorGenRevGradFile emits a SELF-CONTAINED <fn>_RGrd.m (the wrapper
        % and the adjoint computation in one file) using the same
        % global ADiGator_<fn> / ADiGator_LoadData / Gator*Data boilerplate the
        % patch/prune stages expect, so it embeds with main == m: the pipeline
        % patches the single file in place rather than embedding a derivative
        % into a separate wrapper (see the selfContained branch below).
        rev = adigatorGenRevGradFile(UserFunName,UserFunInputs,varargin{:});
        [~,revname] = fileparts(rev.FunctionFile);
        info = struct('GenFiles', struct(...
            'main',rev.FunctionFile,'m',rev.FunctionFile,'mat',rev.MatFile,...
            'name',revname,'dername',revname,'func',{{revname}},...
            'path',rev.Path,'data',{{}},'datapath',{{}},'selfContained',true));
    otherwise
        error('Unsupported derivative type: %s', DerType);
end

switch opts.embed_mode
    case 'c' % classical mode, no embedding
        fprintf('User selected classical mode, no processing needed, exiting.\n');
        return;
    case 'i' % inline mode
        inline = true; coderload = false;
        fprintf('User selected inline mode (static data embedded in a function).\n');
    case 'l' % coderload
        coderload = true; inline = false;
        fprintf('User selected coderload mode.\n')
    otherwise
        error('unknown embed_mode option %s',opts.embed_mode);
end

%% ------------ Post-process according to user instructions -------------%%
% this is a structure array that includes all the files associated with all
% the derivatives in the form:
% .main - wrapper for calling adigator processing functions - path
% .m    - adigator generated processing of derivative (to be processed for embedding in main) - path
% .mat  - adigator generated static data (to be processed if user options = 'inline') - path
% .name - name of the main file
% .dername - name of the adigator generated processing
% .func - cell with the list of functions inside the .m file
%
% each element of the array is a single derivative (all files are standalone)
AdigatorGeneratedFiles = info.GenFiles;
N_derivs = length(AdigatorGeneratedFiles);

% go through each derivative
for derf = 1:N_derivs
    fprintf('Processing derivative #%d...\n',derf);
    % cleared each iteration so a stale value from a prior derivative can never
    % leak into the embed/ERT-clean step below (the inline/coderload branch sets
    % it for this derivative).
    auxiliary_deriv_filecontents = strings(0,1);

    % R16b (issue #73): a self-contained derivative (the reverse _RGrd file)
    % is both wrapper and computation in one file (main == m), so it is patched
    % in place rather than embedded into a separate wrapper.
    selfContained = isfield(AdigatorGeneratedFiles(derf),'selfContained') ...
        && AdigatorGeneratedFiles(derf).selfContained;

    % A self-contained file may carry NO static data (a fully-vectorized reverse
    % gradient, ANALYSIS §3.5): no .mat, no global/load/Gator*Data. There is
    % nothing to prune or embed - just stamp %#codegen in place and move on.
    if selfContained && (isempty(AdigatorGeneratedFiles(derf).mat) ...
            || ~isfile(AdigatorGeneratedFiles(derf).mat))
        fprintf('\t self-contained, no static data: stamping %%#codegen.\n');
        txt = adigator_patch_derivative(AdigatorGeneratedFiles(derf).main,...
            AdigatorGeneratedFiles(derf).name,{AdigatorGeneratedFiles(derf).name},1);
        writelines(txt,AdigatorGeneratedFiles(derf).main,'WriteMode','overwrite');
        continue
    end

    %%% R7b (issue #21): slim the derivative code BEFORE pruning so the
    %%% now-unreferenced Gator*Data index tables drop in the prune below.
    %%% Opt-in; conservative (leaves the file unsliced on any uncertainty).
    %%% Reverse files (self-contained) are not sliced yet (the wrapper-demand
    %%% model assumes a separate wrapper); reverse slimming is deferred (R18+).
    slim = struct('sliced',false,'dropped',0,'collapsed',0,'checked',false,'reason','');
    if opts.slim_embed && ~selfContained
        fprintf('\t Slimming derivative code (slim_embed)... ');
        slim = adigatorSlimEmbeddedDeriv(AdigatorGeneratedFiles(derf),UserFunInputs);
        if slim.sliced || slim.collapsed > 0
            chk = '';
            if slim.checked; chk = ' (round-trip verified)'; end
            fprintf('removed %d statement(s), collapsed %d union copy(ies)%s.\n',...
                slim.dropped,slim.collapsed,chk);
        else
            fprintf('no slimming (%s).\n',slim.reason);
        end
    end

    %%% process the data file to prune it of unnecessary data for derivative evaluation
    fprintf('\t Processing static data file (cleaning up unnecessary data)... ');
    tmp_adigator_struct = load(AdigatorGeneratedFiles(derf).mat); % load data
    %%% R7b data half (issue #21): when slim_embed actually rewrote the code,
    %%% scan the now-slimmed file so the prune below drops the index tables the
    %%% surviving code no longer references. Any failure -> empty map -> the
    %%% prune keeps all Index* (unchanged behaviour); never blocks generation.
    referenced = struct();
    if opts.slim_embed && (slim.sliced || slim.collapsed > 0)
        try
            referenced = adigatorReferencedIndex(readlines(AdigatorGeneratedFiles(derf).m),...
                                                 AdigatorGeneratedFiles(derf).func);
        catch
            referenced = struct();
        end
    end
    tmp_adigator_struct = prune_adigator_mat(tmp_adigator_struct,AdigatorGeneratedFiles(derf).func,referenced); % remove unnecessary fields
    save(AdigatorGeneratedFiles(derf).mat,'-struct','tmp_adigator_struct'); % replace existing mat file with the relevant fields only
    fprintf('done.\n');
    % v2.0 (B6): pruning strips the re-differentiation metadata that
    % adigator stores for higher-order passes; make that explicit
    fprintf(['\t\t NOTE: the pruned %s keeps runtime data only and can no ',...
        'longer be used as input to another adigator differentiation.\n'],...
        AdigatorGeneratedFiles(derf).mat);

    % M8: the derivative source (.m) and static-data (.mat) files are the only
    % thing to regenerate from if the embed below errors. Collect them here and
    % delete them ONLY after every writelines has succeeded (see end of loop) -
    % deleting them up-front, as before, left a truncated wrapper and nothing to
    % recover from on any mid-embed failure.
    filesToDelete = {};

    %%% if user requests inline option, the data is loaded from a function
    if inline
        % generate new data function (tmp)
        fprintf('\t\t Generating data function(s) as requested in inline mode...');
        for funidx=1:numel(AdigatorGeneratedFiles(derf).func)
            AdigatorGeneratedFiles(derf).data{funidx} = ['data_',AdigatorGeneratedFiles(derf).func{funidx}];
            AdigatorGeneratedFiles(derf).datapath{funidx} = structure_to_embed_mfile(AdigatorGeneratedFiles(derf).data{funidx},...
                                                            tmp_adigator_struct.(AdigatorGeneratedFiles(derf).func{funidx}),AdigatorGeneratedFiles(derf).path);
        end
        fprintf('done.\n');

        % patch the adigator generated derivative file
        fprintf('\t Processing ADiGator derivative file... ');
        auxiliary_deriv_filecontents = adigator_patch_derivative(AdigatorGeneratedFiles(derf).m,AdigatorGeneratedFiles(derf).dername,AdigatorGeneratedFiles(derf).func,0,AdigatorGeneratedFiles(derf).data);
        fprintf('done.\n');

        % cleanup (derivative file) - kept for a self-contained file, which is
        % rewritten in place by the embed step below. M8: deferred to loop end.
        if ~selfContained; filesToDelete{end+1} = AdigatorGeneratedFiles(derf).m; end %#ok<AGROW> bounded by file count
        % cleanup (static data file) - deferred to loop end (M8)
        filesToDelete{end+1} = AdigatorGeneratedFiles(derf).mat; %#ok<AGROW> bounded by file count
    end

    %%% if user requests the coderload option, the data is loaded at compile time from a file
    if coderload
        % patch the adigator generated derivative file
        fprintf('\t Processing ADiGator derivative file... ');
        auxiliary_deriv_filecontents = adigator_patch_derivative(AdigatorGeneratedFiles(derf).m,AdigatorGeneratedFiles(derf).dername,AdigatorGeneratedFiles(derf).func,0);
        fprintf('done.\n');

        % cleanup (remove derivative file) - kept for a self-contained file,
        % which is rewritten in place by the embed step below. M8: deferred to
        % loop end (the .mat is retained: coderload reads it via coder.load).
        if ~selfContained; filesToDelete{end+1} = AdigatorGeneratedFiles(derf).m; end %#ok<AGROW> bounded by file count
    end

    %%% #80 (Gap A): strip the dead output-index metadata so the embeddable file
    %%% codegens under strict Embedded Coder (ERT). The core printer emits each
    %%% order's size/location by reading the previous order's field on the output
    %%% struct (y.dxdx_size = [y.dx_size, ...]); ERT forbids adding a field after
    %%% the struct is read. These fields are dead in the terminal wrapper
    %%% (hardcoded index lists), so we remove them rather than rewrite dead code
    %%% to be legal. slim_embed=1 already removes them via slicing; this makes it
    %%% unconditional for the embeddable modes. (Classic mode 'c' returns before
    %%% this point, so the raw form stays observable there.)
    % (empty only on a path that produced no derivative subfunction; the
    % inline/coderload branch above always sets it for an embeddable mode.)
    if ~isempty(auxiliary_deriv_filecontents)
        auxiliary_deriv_filecontents = adigatorStripDeadOutputIndices(auxiliary_deriv_filecontents);
    end

    %%% embed: forward embeds the patched derivative into a separate wrapper; a
    %%% self-contained reverse file IS the wrapper, so write the already-patched
    %%% (%#codegen + persistent/coder.load or inline-data) contents back in place.
    fprintf('\t Embed data and derivative functions... ');
    if selfContained
        writelines(auxiliary_deriv_filecontents,AdigatorGeneratedFiles(derf).main,'WriteMode','overwrite');
    else
        % patch main wrapper with %#codegen
        main_deriv_filecontents = adigator_patch_derivative(AdigatorGeneratedFiles(derf).main,AdigatorGeneratedFiles(derf).name,{AdigatorGeneratedFiles(derf).name},1);
        % write to file
        writelines(main_deriv_filecontents,AdigatorGeneratedFiles(derf).main,'WriteMode','overwrite');
        writelines(["";""],AdigatorGeneratedFiles(derf).main,'WriteMode','append');
        writelines(auxiliary_deriv_filecontents,AdigatorGeneratedFiles(derf).main,'WriteMode','append');
    end
    if inline
        for dataf = 1:length(AdigatorGeneratedFiles(derf).data)
            tmp_data = readlines(AdigatorGeneratedFiles(derf).datapath{dataf});
            writelines(tmp_data,AdigatorGeneratedFiles(derf).main,'WriteMode','append');
            delete(AdigatorGeneratedFiles(derf).datapath{dataf});
        end
    end

    % M8: the wrapper is now fully written - reaching here means every writelines
    % above succeeded. Only now remove the deferred source files; on any earlier
    % error these are skipped, so the .m/.mat survive for regeneration.
    for df = 1:numel(filesToDelete)
        delete(filesToDelete{df});
    end

    fprintf('done.\n')
end

end

% prune_adigator_mat was extracted to embedding/prune_adigator_mat.m so it
% can be unit-tested (see tests/unit/UPruneMatTest.m).

