% function [Jac,Fun] = gapfun_Grd(w,z)
% 
% Jacobian wrapper file generated by ADiGator
% ©2010-2014 Matthew J. Weinstein and Anil V. Rao
% ©2025 Pedro Lourenço @ GMV
% This version of ADiGator may be obtained at https://github.com/pdlourenco/adigator-embedded 
% Contact: mweinstein@ufl.edu
% Bugs/suggestions may be reported to the sourceforge forums
%                    DISCLAIMER
% ADiGator is a general-purpose software distributed under the GNU General
% Public License version 3.0. While the software is distributed with the
% hope that it will be useful, both the software and generated code are
% provided 'AS IS' with NO WARRANTIES OF ANY KIND and no merchantability
% or fitness for any purpose or application.

function [Jac,Fun] = gapfun_Grd(w,z)
gator_z.f = z;
gator_z.dz = ones(2,1);
f = gapfun_ADiGatorGrd(w,gator_z);
Jac = reshape(f.dz,[2 1]);
Fun = f.f;
end