function cleanup = mcAddPaths()
%MCADDPATHS  Put the Monte-Carlo harness and toolbox folders on the path.
%
% Returns an onCleanup object that restores the original path when it goes
% out of scope. Used by mcCampaign so the harness runs from a plain MATLAB
% session; MCSmokeTest uses PathFixture instead.
thisDir = fileparts(mfilename('fullpath'));      % tests/montecarlo
root    = fileparts(fileparts(thisDir));         % repo root
oldpath = path;
addpath( ...
    thisDir, ...
    fullfile(thisDir, 'generators'), ...
    fullfile(thisDir, 'oracles'), ...
    fullfile(root, 'tests', 'helpers'), ...
    root, ...
    fullfile(root, 'lib'), ...
    fullfile(root, 'lib', 'cadaUtils'), ...
    fullfile(root, 'util'), ...
    fullfile(root, 'embedding'));
cleanup = onCleanup(@() path(oldpath));
end
