classdef IGuideFixturesTest < matlab.unittest.TestCase
    % IGuideFixturesTest  Keeps the user-guide code-sample golden fixtures
    % (ADR-0025, issue #139) in sync with live generator output.
    %
    % The guide loads excerpts from tests/fixtures/guide/*.m via \lstinputlisting
    % keyed on `% BEGIN-<tag>` / `% END-<tag>` marker ranges. This test is the
    % ADR-0025 tripwire: if a generator change alters the emitted reverse-gradient
    % code, the committed fixture (and therefore the printed guide sample) would
    % silently drift; instead this fails until the fixture is regenerated by
    % tests/fixtures/guide/capture_guide_samples.m. It also asserts the marker
    % pair the guide keys off is present (a missing marker is a guide build error).

    methods (TestClassSetup)
        function addPaths(tc)
            import matlab.unittest.fixtures.PathFixture
            testDir = fileparts(mfilename('fullpath'));
            root = fileparts(fileparts(testDir));
            tc.applyFixture(PathFixture(root));
            tc.applyFixture(PathFixture(fullfile(root,'lib')));
            tc.applyFixture(PathFixture(fullfile(root,'lib','cadaUtils')));
            tc.applyFixture(PathFixture(fullfile(root,'util')));
            tc.applyFixture(PathFixture(fullfile(root,'examples','gradients','logsumexp')));
        end
    end

    methods (TestMethodSetup)
        function workInTempFolder(tc)
            import matlab.unittest.fixtures.WorkingFolderFixture
            tc.applyFixture(WorkingFolderFixture);
        end
    end

    methods (Test)
        function reverseGradientFixtureMatchesGenerator(tc)
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            fixture = fullfile(root,'tests','fixtures','guide','lse_cost_RGrd.m');
            tc.assertEqual(exist(fixture,'file'), 2, ...
                'guide fixture tests/fixtures/guide/lse_cost_RGrd.m is missing');

            % regenerate the same reverse gradient capture_guide_samples.m captures
            n = 4;
            gx = adigatorCreateDerivInput([n 1],'x');
            gw = adigatorCreateAuxInput([n 1]);
            adigatorGenRevGradFile('lse_cost', {gx, gw}, ...
                adigatorOptions('overwrite',1,'echo',0));
            fresh = trimTrailingBlank(readlines('lse_cost_RGrd.m'));

            % the committed fixture is that output with the marker lines inserted;
            % stripping the markers must reproduce the generator output exactly
            committed = readlines(fixture);
            markerLine = startsWith(strip(committed), "% BEGIN-") | ...
                         startsWith(strip(committed), "% END-");
            committed = trimTrailingBlank(committed(~markerLine));

            tc.verifyEqual(committed, fresh, ...
                ['guide fixture lse_cost_RGrd.m is out of sync with ', ...
                 'adigatorGenRevGradFile; regenerate via ', ...
                 'tests/fixtures/guide/capture_guide_samples.m']);

            % the markers the guide's \lstinputlisting range keys off must exist
            fx = strip(readlines(fixture));
            tc.verifyTrue(any(strcmp(fx, "% BEGIN-rgrd-core")), ...
                'BEGIN-rgrd-core marker missing (guide \lstinputlisting range would be empty/error)');
            tc.verifyTrue(any(strcmp(fx, "% END-rgrd-core")), ...
                'END-rgrd-core marker missing');
        end
    end
end

% ---- helpers ----
function s = trimTrailingBlank(s)
% drop trailing all-whitespace lines so an incidental final newline does not
% break the exact comparison
while ~isempty(s) && strlength(strip(s(end))) == 0
    s(end) = [];
end
end
