function cadaErrorSymbolicIndex()
%CADAERRORSYMBOLICINDEX  Actionable error for a data-dependent subscript.
%   Raised when a variable is indexed by a value computed at runtime (a
%   "symbolic" / data-dependent subscript, e.g. A(k,:) where k is not a
%   compile-time constant). Static forward AD by source transformation cannot
%   differentiate this: the derivative sparsity pattern must be fixed at
%   generation time, but a runtime index makes it runtime-dependent.
%
%   By design this is a hard error, never a plausible-but-wrong derivative
%   (docs/REVIEW_CONTEXT.md principle 1). This helper replaces the former
%   cryptic message with one that names the construct and points to the
%   logical-weight-sum rewrite. B20 (docs/ANALYSIS.md Sec 1.3c), ADR-0024.
%
% Copyright GMV. Distributed under the GNU General Public License v3.0.

msg = [ ...
    'ADiGator cannot differentiate an index that is computed at runtime ', ...
    '(a data-dependent / "symbolic" subscript, e.g. A(k,:) where k is not a ', ...
    'compile-time constant): the derivative sparsity pattern must be known ', ...
    'at generation time, but a runtime index would make it ', ...
    'runtime-dependent.', newline, newline, ...
    'Rewrite the dynamic index as a sum with logical weights, so the ', ...
    'subscript is constant and the selection is done by an ==, e.g.', newline, ...
    '    v = 0;', newline, ...
    '    for k = 1:size(A,1)', newline, ...
    '        v = v + (idx == k) .* A(k,:);', newline, ...
    '    end', newline, newline, ...
    'This selects the same row/element without a data-dependent subscript. ', ...
    'If the index is instead a loop counter, use a "for" loop rather than a ', ...
    '"while" loop: ADiGator unrolls "for" loops (so the counter is a ', ...
    'compile-time constant) but does not unroll "while" loops.', newline, newline, ...
    'See the user guide (Limitations) and docs/ANALYSIS.md B19/B20.'];
error('adigator:symbolicIndex', '%s', msg);
end
