function output = adigatorGenJacFile(UserFunName,UserFunInputs,varargin)
% ADiGator Jacobian File Generation Function: this function is used when
% you wish to generate a Jacobian of a function with an input variable of
% differentiation (and any auxiliary inputs), and a single output. This
% simply calls the function adigator and creates a wrapper function s.t.
% the input of the resulting file is the same as the input to the original
% user function, but outputs both the Jacobian and the original output.
%
% ------------------------------ Usage -----------------------------------
% output = adigatorGenJacFile(UserFunName,UserFunInputs)
%                   or
% output = adigatorGenJacFile(UserFunName,UserFunInputs,Options)
%                   or
% output = adigatorGenJacFile(UserFunName,UserFunInputs,Options,NameAppendix)
%
% ------------------------ Input Information -----------------------------
% UserFunName: String name of the user function to be differentiated
%
% UserFunInputs: N x 1 cell array containing the inputs to the UserFun
%                - the input (or cell array element/structure field)
%                corresponding to the variable of differentiation must be
%                created using the adigatorCreateDerivInput function.
%                i.e. if the first input is the variable of
%                differentiation, then the first input must be created
%                using adigatorCreateDerivInput prior to calling adigator.
%                - any other numeric inputs should be defined as they will
%                be when calling the derivative function. These will be
%                assumed to have fixed sizes and zero locations, but the
%                non-zero locations may change values. If the values are
%                always fixed, then adigatorOptions may be used to change
%                the handling of these auxiliary inputs.
%                - auxiliary inputs may also be created using the
%                adigatorCreateAuxInput function.
%
% Options (optional): option structure generated by adigatorOptions
%                     function
%
% NameAppendix (optional): appendix to the name of the generated Jac files
%
% ------------------------ Output Information ----------------------------
% Assuming UserFunName = 'myfun', then the Jacobian is named 'myfun_Jac' or
% 'myfun_NameAppendix' if user provided. 
% The output of adigatorGenJacFile is the structure:
%     output.FunctionFile = 'myfun'
%     output.JacobianFile = 'myfun_Jac' | 'myfun_NameAppendix'
%     output.JacobianCSC = the CSC sparse pattern {Size, ColPtr, RowIdx, Nnz,
%         IndexBase} of the returned Jacobian (GradientCSC for the scalar-
%         function gradient convention). The sole exported sparse-pattern
%         representation (#192, ADR-0030); rebuild coordinate/sparse forms with
%         adigatorCSCToLocs / adigatorCSCToSparse.
% The generated Jacobian file has the same input structure as the original
% user function. The output of Jacobian file is [Jac, Fun]. With
% der_output='csc', Jac is the Nnz x 1 value vector in CSC order.
%
% ----------------------- Additional Information -------------------------
% The Jacobian is built as a sparse matrix under the condition that
% numel(Jac) >= 250 & nnz(Jac)/numel(Jac) <= 3/4, otherwise it is built as
% a full matrix.
%
% If the output is y, input is x, numel(y) = m, numel(x) = n...
%     case: n > 1, size(Jac) = [m n]
%     case: n = 1, size(Jac) = size(y)
%
% The functions generated Jacobian file is simply wrapper files for the
% ADiGator generated file (named 'myfun_ADiGatorJac')
%
% Copyright 2011-2014 Matthew J. Weinstein and Anil V. Rao
% Distributed under the GNU General Public License version 3.0
%
% see also adigator, adigatorCreateDerivInput, adigatorCreateAuxInput,
% adigatorOptions, adigatorGenHesFile
%
%   Modifications as described below are Copyright Pedro Lourenço and GMV.
%   2025-10  PEDRO LOURENÇO (PADL) - palourenco@gmv.com
%
%   Changelog:
%   2025-10 Pedro Lourenço  v2.0    Store the generated derivative file and
%                                   and the mat file with the static
%                                   derivative data in the user provided
%                                   folder and not necessarily in the 
%                                   calling directory
%                                   Add parser for the user provided options
%                                   Add option for user to specify filename
%                                   Provide the paths to all the generated
%                                   functions and files (.mat and .m)
%                                   Modify output gradients to be in column
%                                   form, i.e. f = df/dx'*x+x'*d2f/dx2*x;
%                                   when computing gradients. Maintaining
%                                   numerator form when computing Hessians and Jacobians
%   2026-06                         Read user option fields with the name
%                                   as given, lower-casing only the
%                                   destination (B12), and normalize
%                                   EMBED_MODE aliases (B11) (PR #8).
%                                   JacobianStructure decomposes unrolled
%                                   nzlocs into the displayed shape when
%                                   the scalar-of-matrix/matrix-of-scalar
%                                   remap fires (B10, PR #5).
%                                   In embed modes, precompute the scatter
%                                   indices at generation time and emit
%                                   them as literal vectors (ANALYSIS.md
%                                   2.1, PR #9).
%                                   Add jac_output='nonzeros': the wrapper
%                                   returns the nonzero vector with the
%                                   constant pattern exported once via
%                                   output.JacobianLocs - no per-call
%                                   dense projection (roadmap R5).
%                                   Honour der_levels: emit the function
%                                   value Fun only when level 0 is requested
%                                   (the first derivative is always
%                                   returned) (roadmap R7a, issue #21).
%   2026-07                         CSC contract (#192, ADR-0030, R31): the
%                                   output form is der_output {matrix,csc}
%                                   ('nonzeros' and the jac_output alias
%                                   removed); export output.JacobianCSC /
%                                   GradientCSC (the sole sparse pattern) in
%                                   both modes; csc mode returns the Nnz x 1
%                                   value vector in CSC order.

%% ~~~~~~~~~~~~~~~~~~~~~~~~~~ OPTIONS SETUP ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ %%
opts = adigatorOptions(); % default options
NameAppendix = 'Jac';
if nargin == 2
  opts.overwrite = 1;
else
    % parse options
    optfields = fieldnames(varargin{1});
    for Fcount = 1:length(optfields)
        % v2.0 (B12 fix): lower-case only the destination field; the user's
        % struct must be read with the field name they actually used
        opts.(lower(optfields{Fcount})) = varargin{1}.(optfields{Fcount});
    end
    if ~any(strcmpi(optfields,'overwrite'))
        opts.overwrite = 1;
    end
    % parse names
    if nargin == 4
        NameAppendix = varargin{2};
    end
end
opts.embed_mode = adigatorNormalizeEmbedMode(opts.embed_mode); % v2.0 (B11 fix)

%% ~~~~~~~~~~~~~~~~~~~~~~~~~~ INPUTS PARSING ~~~~~~~~~~~~~~~~~~~~~~~~~~~ %%
if ~ischar(UserFunName)
  error(['First input to adigator must be string name of function to be ',...
    'differentiated']);
end
JacFileName    = [UserFunName,'_',NameAppendix];         % Name of wrapper file
AdiJacFileName = [UserFunName,'_ADiGator',NameAppendix]; % Name of derivative file

% Quick input check
if ~iscell(UserFunInputs)
  error(['Second input to adigator must be cell array of inputs to ',...
    'the function described by first input string']);
end

% Find derivative input (searches top-level inputs and, recursively,
% struct/cell fields, so the derivative variable may be a struct field -
% issue #24, scope A). derpathStr/derpathSubs give its access path within
% UserFunInputs{derflag}; both are empty when the input is itself the
% derivative variable, in which case behaviour is identical to before.
[derflag, derpathStr, ~, x] = adigatorFindDerivInput(UserFunInputs,'adigatorGenJacFile');

% File checks
if isempty(opts.path) % v2.0 - allow user to specify the path
    CallingDir = cd;
else
    CallingDir = opts.path;
    if ~exist(CallingDir,'dir') % directory does not exist -> create it
        mkdir(CallingDir);
    end
end
% v2.0 - add chosen directory to the path to allow storage
% in userdefined directories
original_path = path();
addpath(CallingDir);

UserFun = str2func(UserFunName);
% Output Check
if nargout(UserFun) ~= 1
  error_restore_path(original_path,'User function must contain single output');
end



% Store the path to the generated files (v2.0)
ADiGator_GeneratedFiles.Jac = fullfile(CallingDir, [JacFileName, '.m']);

if exist(ADiGator_GeneratedFiles.Jac,'file')
  if opts.overwrite
    delete(ADiGator_GeneratedFiles.Jac);
    rehash
  else
    error_restore_path(original_path,['The file ',ADiGator_GeneratedFiles.Jac,' already exists, ',...
      'quitting transformation. To set manual overwrite of file use ',...
      '''''adigatorOptions(''OVERWRITE'',1);''''. Alternatively, delete the ',...
      'existing file and any associated .mat file.']);
  end
end

% Call adigator
try % v2.0 - add try-catch to avoid leaving unnecessary changes to path active
[adiout,FunctionInfo,ADi_DerivFiles(1),ADi_DerivFuns] = adigator(UserFunName,UserFunInputs,AdiJacFileName,opts); % v2.0 - add new output with list of files/functions
catch ME
    path(original_path);
    rethrow(ME);
end

adiout = adiout{1};

% v2.0 - restore the path to its original state
path(original_path);

% #164: reject a non-numeric (struct/cell) user output with an actionable error
% BEFORE opening the wrapper file, so no truncated wrapper is left on disk and
% the failure is not the cryptic downstream "Unrecognized field name 'func'".
% The path is already restored here, so a plain throw is clean.
adigatorAssertNumericOutput(adiout, UserFunName, 'genjac');

fid = fopen(ADiGator_GeneratedFiles.Jac,'w+');
if fid == -1
  error('adigator:genjac:io','could not open ''%s'' for writing',...
    ADiGator_GeneratedFiles.Jac);
end
fidCloser = onCleanup(@() fclose(fid));   % closes on an emission throw

InputStrs = FunctionInfo.Input.Names.';
xstr = InputStrs{derflag};
for I = 1:length(InputStrs)
  InputStrs{I} = [InputStrs{I},','];
end
InputStr1 = cell2mat(InputStrs);
InputStr1(end) = [];

% roadmap R7a (issue #21): DER_LEVELS selects which derivative levels the
% wrapper returns. This generator produces level 1 (the first derivative,
% named by the file appendix - Grd for a gradient, Jac for a Jacobian, per
% C-6; the gradient path calls this generator with NameAppendix='Grd') and
% level 0 (the function value Fun). The first derivative is always returned, so
% DER_LEVELS only toggles whether Fun accompanies it; the default ([]) keeps
% the [<deriv>,Fun] signature. The emission block below assigns the same
% NameAppendix variable, so the signature and body names always match.
jacLevels = adigatorResolveDerLevels(opts.der_levels, 1, 'adigatorGenJacFile');
wantFun   = ismember(0, jacLevels);
jacOut    = {NameAppendix};   % C-6: Grd (gradient) / Jac (Jacobian), via the appendix
if wantFun; jacOut{end+1} = 'Fun'; end
functionstr = ['function [',strjoin(jacOut,','),'] = ',JacFileName,'(',InputStr1,')\n'];

fprintf(fid,['%% ',functionstr,]);
fprintf(fid,'%% \n');

% Print Function Header (#200). Same stamp as the derivative file this wrapper
% calls - it rides out on FunctionInfo(1).Stamp, because B16's cleanup has
% cleared the transformation globals by the time we get here.
cadaPrintGeneratedHeader(fid, JacFileName, adigatorStampOf(FunctionInfo), ...
  adigatorReconstructCall(UserFunName, JacFileName, opts, 'adigatorGenJacFile'));

fprintf(fid,functionstr);
% Change the derivative input.. (x is the located derivative object)
vodname = x.deriv.vodname;
if isempty(derpathStr)
  % derivative variable is the input itself - unchanged behaviour
  fprintf(fid,['gator_',xstr,'.f = ',xstr,';\n']);
  fprintf(fid,['gator_',xstr,'.d',vodname,' = ones(%1.0f,1);\n'],prod(x.func.size));
else
  % derivative variable is carried inside a struct/cell input: copy the
  % container through and overwrite only the derivative field with its
  % {.f,.d<vod>} seed (issue #24, scope A)
  seedvar = ['gator_',xstr,'_seed'];
  fprintf(fid,['gator_',xstr,' = ',xstr,';\n']);
  fprintf(fid,[seedvar,'.f = ',xstr,derpathStr,';\n']);
  fprintf(fid,[seedvar,'.d',vodname,' = ones(%1.0f,1);\n'],prod(x.func.size));
  fprintf(fid,['gator_',xstr,derpathStr,' = ',seedvar,';\n']);
end

InputStrs{derflag} = ['gator_',xstr,','];
InputStr2 = cell2mat(InputStrs);
InputStr2(end) = [];

ystr = FunctionInfo.Output.Names{1};
% Call the ADiGatorJac file
fprintf(fid,[ystr,' = ',AdiJacFileName,'(',InputStr2,');\n']);

% v2.0
% following the conventions on https://en.wikipedia.org/wiki/Matrix_calculus

%%% SCALAR FUNCTION OF VECTOR VARIABLE (GRADIENT)
% f: Rn -> R
% x in Rn
%
% Gradient_x(f) = [df/dx1
%                  ...
%                  df/dxn]
%
% size(Gradient_x(f)) = [length(x) length(f)]
%
% usage in computations: Gradient_x(f)' * x
%%% VECTOR FUNCTION OF VECTOR VARIABLE (JACOBIAN)
% f: Rn -> Rm
% x in Rn
%
% Jacobian(f)_x = [df1/dx1  ... df1/dxn
%                  ...
%                  dfm/dx1   ... dfm/dxn]
%
% size(Jacobian_x(f)) = [length(f) length(x)]   % m x n (contract C-1)
%
% usage in computations: Jacobian_x(f) * x

%%% GENERALIZATION
% f: Rnxm -> Rrxc
% x in Rnxm
%
%		    c=1	    c=1	    c>1	    c>1
%		    r=1	    r>1	    r=1	    r>1
% n=1	m=1	1 x 1	r x 1	c x 1	r x c
% n=1	m>1	m x 1	r x m	c x m	r*c x m
% n>1	m=1	n x 1	r x n	c x n	r*c x n
% n>1	m>1	n x m	r x n*m	c x n*m	r*c x n*m

% Check to see how many non-zeros in Jacobian
xsize = x.func.size;
ysize = adiout.func.size;
dydxsize = [prod(ysize), prod(xsize)];
dydxnumel  = dydxsize(1)*dydxsize(2);
remapcase = 0; % v2.0 (B10 fix): remember the shape remap for the CSC pattern
if dydxsize(1) == 1 && all(xsize>1) % scalar function of matrix variable
  remapcase = 1;
  dydxsize = xsize;
  ysize = [xsize(1) 1];
  xsize = [xsize(2) 1];
elseif dydxsize(2) == 1 && all(ysize>1) % matrix function of scalar variable
  remapcase = 2;
  dydxsize = ysize;
  xsize = [ysize(2) 1];
  ysize = [ysize(1) 1];
end
dydxnnz  = size(adiout.deriv.nzlocs,1);
% If dydx has => 250 elements and has <= 75% nonzeros, project into sparse
% matrix, otherwise project into full matrix.
dy = [ystr,'.d',vodname];
% v2.0 (ANALYSIS.md §2.1): in embed modes, precompute the scatter indices
% at generation time and emit them as a literal vector. This removes the
% per-call _location index arithmetic from the wrapper, and the indices
% become compile-time constants in the generated C code. nzlocs columns are
% linear indices into the unrolled [prod(ysize) x prod(xsize)] Jacobian, so
% the displayed-shape linear index is direct (remap cases) or the standard
% column-major combination.
embedscatter = opts.embed_mode ~= 'c';
if embedscatter
  if remapcase == 1      % scalar function of matrix variable: index is x
    linidx = adiout.deriv.nzlocs(:,2);
  elseif remapcase == 2  % matrix function of scalar variable: index is y
    linidx = adiout.deriv.nzlocs(:,1);
  else
    linidx = (adiout.deriv.nzlocs(:,2)-1)*dydxsize(1) + adiout.deriv.nzlocs(:,1);
  end
  scatteridx = mat2str(linidx(:).');
else
  scatteridx = [dy,'_location']; % single-column cases only (see below)
end
% v2.0 (#192, ADR-0030): the CSC pattern of the RETURNED derivative. nzlocs are
% in VALUE order; decompose remapped unrolled indices into displayed subscripts
% (same mapping as the structure build below), then orient to the returned
% convention - a scalar-function gradient is returned as [n,1], not the [1,n]
% Jacobian, so its pattern is transposed (ADR-0030 D7).
if remapcase == 1
  [csrows,cscols] = ind2sub(dydxsize, adiout.deriv.nzlocs(:,2));
elseif remapcase == 2
  [csrows,cscols] = ind2sub(dydxsize, adiout.deriv.nzlocs(:,1));
else
  csrows = adiout.deriv.nzlocs(:,1);
  cscols = adiout.deriv.nzlocs(:,2);
end
if dydxsize(1) == 1 && ~strcmp(NameAppendix,'Jac')
  % scalar function, gradient convention -> returned [n,1] (D7). Also covers
  % scalar-of-scalar ([1,1], orientation-neutral) so the exported role follows
  % the requested naming convention (GradientCSC), not the shape.
  cscRole = 'Gradient';
  cscSize = [dydxsize(2), 1];
  cscLocs = [cscols(:), ones(numel(cscols),1)];
else
  cscRole = 'Jacobian';
  cscSize = dydxsize;
  cscLocs = [csrows(:), cscols(:)];
end
[JacCSC, cscperm, cscisid] = adigatorBuildCSC(cscSize, cscLocs);

%v2.0:	process this to output Jacobians and Gradients correctly, as shown above
% #192/ADR-0030: der_output selects this (top-order) output's FORM. 'csc'
% returns the structurally-possible-nonzero VALUE vector in CSC order (values
% only); the constant pattern is exported once as output.<Role>CSC. The native
% value stream (y.d<vod> in nzlocs order) is already CSC order for every current
% shape (verified via the identity flag), so this is dy(:) with an ASSERTED
% identity; a future nzlocs-ordering change that broke it emits a constant
% gather instead - never a runtime sort. The Hessian reads der_output only, so
% this never flips the Hessian's form (ADR-0022, decision b).
if strcmp(opts.der_output,'csc')
  if cscisid
    fprintf(fid,[NameAppendix,' = ',dy,'(:);\n']);
  else
    fprintf(fid,[NameAppendix,' = ',dy,'(',mat2str(cscperm(:).'),');\n']);
  end
elseif dydxnnz == dydxnumel % all elements are nonzero
    if dydxsize(1) == 1 % the function is a scalar, use the Gradient convention if user selected
        if strcmp(NameAppendix,'Jac') % Use Jacobian convention
            fprintf(fid,[NameAppendix,' = reshape(',dy,',[%1.0f %1.0f]);\n'],[dydxsize(1) dydxsize(2)]);
        else
            fprintf(fid,[NameAppendix,' = reshape(',dy,',[%1.0f %1.0f]);\n'],[dydxsize(2) dydxsize(1)]);
        end
    else % the function is not a scalar -> use the Jacobian convention
        fprintf(fid,[NameAppendix,' = reshape(',dy,',[%1.0f %1.0f]);\n'],dydxsize);
    end
elseif dydxsize(1) == 1 && dydxsize(2) == 1 % function and variable are scalars
  fprintf(fid,[NameAppendix,' = ',dy,';\n']);
elseif dydxsize(1) == 1 % function is scalar -> use Gradient convention if user selected Gradient
    if strcmp(NameAppendix,'Jac') % Use Jacobian convention
        fprintf(fid,[NameAppendix,' = zeros(1,%1.0f);'],dydxsize(2));
    else
        fprintf(fid,[NameAppendix,' = zeros(%1.0f,1);'],dydxsize(2));
    end
    fprintf(fid,[NameAppendix,'(',scatteridx,') = ',dy,';\n']);
elseif dydxsize(2) == 1 % variable is scalar -> use Jacobian convention
  fprintf(fid,[NameAppendix,' = zeros(%1.0f,1);'],dydxsize(1));
  fprintf(fid,[NameAppendix,'(',scatteridx,') = ',dy,';\n']);
elseif embedscatter % matrix Jacobian, embed modes: literal linear scatter
  fprintf(fid,[NameAppendix,' = zeros(%1.0f,%1.0f);\n'],dydxsize);
  fprintf(fid,[NameAppendix,'(',scatteridx,') = ',dy,';\n']);
else % Jacobian is a matrix -> Jacobian convention (classic runtime indexing)
  dyloc = [dy,'_location'];
  if ~any(ysize == 1)
    % Output is matrix
    fprintf(fid,['funloc = (',dyloc,'(:,2)-1)*%1.0f + ',dyloc,'(:,1);\n'],ysize(1));
    rowstr = 'funloc';
    if ~any(xsize == 1)
      % Input is matrix
      fprintf(fid,['varloc = (',dyloc,'(:,4)-1)*%1.0f + ',dyloc,'(:,3);\n'],xsize(1));
      colstr = 'varloc';
    else
      colstr = [dyloc,'(:,3)'];
    end
  else
    rowstr = [dyloc,'(:,1)'];
    if ~any(xsize == 1)
      % Input is matrix
      fprintf(fid,['varloc = (',dyloc,'(:,3)-1)*%1.0f + ',dyloc,'(:,2);\n'],xsize(1));
      colstr = 'varloc';
    else
      colstr = [dyloc,'(:,2)'];
    end
  end
  if dydxnumel >= 250 && dydxnnz/dydxnumel <= 3/4 && opts.embed_mode == 'c' % v2.0 - only allow sparse matrices if in classic mode (no embed)
    % Project Sparse
    fprintf(fid,[NameAppendix,' = sparse(',rowstr,',',colstr,',',dy,',%1.0f,%1.0f);\n'],dydxsize);
  else
    % Project Full
    fprintf(fid,[NameAppendix,' = zeros(%1.0f,%1.0f);\n'],dydxsize);
    fprintf(fid,[NameAppendix,'((',colstr,'-1)*%1.0f+',rowstr,') = ',dy,';\n'],dydxsize(1));
  end
end
if wantFun % roadmap R7a (issue #21): emit Fun only when level 0 is requested
  fprintf(fid,['Fun = ',ystr,'.f;\n']);
end
fprintf(fid,'end');
clear fidCloser;   % flush + close now; onCleanup still closes on any throw above
rehash

%% --------------------- OUTPUT PROCESSING ------------------------------%%
output.FunctionFile = UserFunName;
output.JacobianFile = JacFileName;

% first derivative - Jacobian (v2.0)
output.GenFiles(1) = ADi_DerivFiles(1);
output.GenFiles(1).main = ADiGator_GeneratedFiles.Jac;
output.GenFiles(1).name = JacFileName;
output.GenFiles(1).func = ADi_DerivFuns;

% v2.0 (#192, ADR-0030): CSC is the sole exported pattern, in BOTH matrix and
% csc modes, describing the RETURNED derivative's shape/convention (Jacobian, or
% Gradient for the scalar-function gradient convention - built above with the
% [n,1] orientation and the remapcase-aware displayed subscripts, then
% canonicalized by adigatorBuildCSC). Host code can rebuild coordinate/sparse
% forms with adigatorCSCToLocs / adigatorCSCToSparse.
output.([cscRole,'CSC']) = JacCSC;

if opts.echo
  fprintf(['\n<strong>adigatorGenJacFile</strong> successfully generated Jacobian wrapper file: ''',JacFileName,''';\n\n']);
end