% function [Grd,Fun] = gapfun_Grd(w,z)
% 
% Gradient wrapper file generated by ADiGator
% 
% gapfun_Grd -- GENERATED FILE. Do not edit; regenerate instead.
% Edits are lost the next time this file is generated.
%
% ADiGator 2.0 (GMV embedded fork) -- generated 2026-08-04T18:14:32Z
% Generation id: 3805ea2a443df6ae  (tool version + options + source contents)
%
% Reconstruct with:
%   adigatorGenDerFile_embedded('gradient', 'gapfun', <inputs>, ...
%       adigatorOptions('embed_mode','i', 'slim_embed',0))
%
%   where <inputs> is the cell of adigatorCreateDerivInput /
%   adigatorCreateAuxInput arguments the function was differentiated at.
%
% Issues and questions: https://github.com/pdlourenco/adigator-embedded/issues
%
% Produced by ADiGator, distributed under the GNU General Public License
% version 3.0, in the hope that it is useful but with NO WARRANTIES OF ANY
% KIND and no merchantability or fitness for any purpose or application.
% ©2010-2014 Matthew J. Weinstein and Anil V. Rao
% ©2025-2026 Pedro Lourenço and GMV (embedded fork additions)

function [Grd,Fun] = gapfun_Grd(w,z)
%#codegen
gator_z.f = z;
gator_z.dz = ones(2,1);
f = gapfun_ADiGatorGrd(w,gator_z);
Grd = reshape(f.dz,[2 1]);
Fun = f.f;
end

% derivative body, generated by ADiGator (see the header above)

function f = gapfun_ADiGatorGrd(w,z)
%#codegen
ADiGator_gapfun_ADiGatorGrd = coder.const(data_gapfun_ADiGatorGrd());
Gator1Data = coder.const(ADiGator_gapfun_ADiGatorGrd.Gator1Data);
% ADiGator Start Derivative Computations
cadainput3_1.dz = z.dz; cadainput3_1.f = z.f;
%User Line: cadainput3_1 = z;
cadaoutput3_1 = ADiGator_setfun(cadainput3_1);
% Call to function: setfun
zaux.dz = cadaoutput3_1.dz; zaux.f = cadaoutput3_1.f;
%User Line: zaux = cadaoutput3_1;
cadainput2_1.dz = z.dz; cadainput2_1.f = z.f;
%User Line: cadainput2_1 = z;
cadaoutput2_1 = ADiGator_conefun(cadainput2_1);
% Call to function: conefun
cada1f1 = w.';
cada1td1 = zeros(2,2);
cada1td1(Gator1Data.Index1) = cadaoutput2_1.dz;
cada1td1 = cada1f1*cada1td1;
cada1td1 = cada1td1(:);
cada1f2dz = cada1td1(Gator1Data.Index2);
cada1f2 = cada1f1*cadaoutput2_1.f;
cada1f3dz = z.dz;
cada1f3 = z.f.';
cada1td2 = zeros(2,2);
cada1td2(Gator1Data.Index3) = cada1f3dz;
cada1td2 = zaux.f.'*cada1td2;
cada1td1 = cada1td2(Gator1Data.Index4);
cada1td1 = cada1td1(:);
cada1td2 = zeros(2,2);
cada1td2(Gator1Data.Index5) = zaux.dz;
cada1td2 = cada1f3*cada1td2;
cada1td2 = cada1td2(:);
cada1td1 = cada1td1 + cada1td2(Gator1Data.Index6);
cada1f4dz = cada1td1;
cada1f4 = cada1f3*zaux.f;
cada1td1 = cada1f2dz;
cada1td1 = cada1td1 + cada1f4dz;
f.dz = cada1td1;
f.f = cada1f2 + cada1f4;
%User Line: f=w'*cadaoutput2_1 +z'*zaux;
end
function y = ADiGator_conefun(z)
%#codegen
ADiGator_gapfun_ADiGatorGrd = coder.const(data_ADiGator_conefun());
Gator1Data = coder.const(ADiGator_gapfun_ADiGatorGrd.Gator1Data);
% ADiGator Start Derivative Computations
H.f = eye(2);
%User Line: H=eye(2);
g.f = ones(2,1);
%User Line: g=ones(2,1);
cadainput3_1.dz = z.dz; cadainput3_1.f = z.f;
%User Line: cadainput3_1 = z;
cadaoutput3_1 = ADiGator_setfun(cadainput3_1);
% Call to function: setfun
cada1td1 = zeros(2,2);
cada1td1(Gator1Data.Index1) = cadaoutput3_1.dz;
cada1td1 = H.f*cada1td1;
cada1td1 = cada1td1(:);
cada1f1dz = cada1td1(Gator1Data.Index2);
cada1f1 = H.f*cadaoutput3_1.f;
y.dz = cada1f1dz;
y.f = cada1f1 - g.f;
%User Line: y=H*cadaoutput3_1-g;
end
function y = ADiGator_setfun(z)
%#codegen
ADiGator_gapfun_ADiGatorGrd = coder.const(data_ADiGator_setfun());
Gator1Data = coder.const(ADiGator_gapfun_ADiGatorGrd.Gator1Data);
% ADiGator Start Derivative Computations
y.dz = z.dz; y.f = z.f;
%User Line: y = z;
end

function S = data_gapfun_ADiGatorGrd()
%#codegen
% Auto-generated by structure_to_embed_mfile
% Helper file for ADiGator generated derivatives
S = struct();
S.Gator1Data = struct();
S.Gator1Data.Index1 = uint32(reshape([1 4 ], 2, 1));
S.Gator1Data.Index2 = uint32(reshape([1 2 ], 2, 1));
S.Gator1Data.Index3 = uint32(reshape([1 4 ], 2, 1));
S.Gator1Data.Index4 = uint32(reshape([1 2 ], 2, 1));
S.Gator1Data.Index5 = uint32(reshape([1 4 ], 2, 1));
S.Gator1Data.Index6 = uint32(reshape([1 2 ], 2, 1));
S.Gator1Data.Index7 = uint32(reshape([1 2 ], 2, 1));
end
function S = data_ADiGator_conefun()
%#codegen
% Auto-generated by structure_to_embed_mfile
% Helper file for ADiGator generated derivatives
S = struct();
S.Gator1Data = struct();
S.Gator1Data.Index1 = uint32(reshape([1 4 ], 2, 1));
S.Gator1Data.Index2 = uint32(reshape([1 4 ], 2, 1));
end
function S = data_ADiGator_setfun()
%#codegen
% Auto-generated by structure_to_embed_mfile
% Helper file for ADiGator generated derivatives
S = struct();
S.Gator1Data = struct();
S.Gator1Data.Index1 = zeros(0, 0, 'uint32');
end
