classdef USlimDerivFileTest < matlab.unittest.TestCase
    % USlimDerivFileTest  Unit tests for the interprocedural field-slice
    % (issue #44 item 1; ADR-0009): adigatorSlimDerivFile splits a multi-
    % subfunction generated _ADiGator* file into its per-function blocks, runs
    % a forward worklist that pushes the result-struct fields a caller reads at
    % a kept call site as demand on the callee, field-slices each block under
    % the per-function closure gate, and reassembles - dropping dead value
    % chains and unread output fields in EVERY function. For a single-derivative
    % -function file it delegates to adigatorSlimDerivBody (proven path). Text-
    % in / text-out on hand-written snippets; no toolbox, no file I/O.

    methods (TestClassSetup)
        function addPaths(tc)
            import matlab.unittest.fixtures.PathFixture
            testDir = fileparts(mfilename('fullpath'));
            root = fileparts(fileparts(testDir));
            tc.applyFixture(PathFixture(fullfile(root,'util')));
        end
    end

    methods (Test)
        function slicesAcrossTheCall(tc)
            % main demands {f,dx}: its own .dx_location/.dx_size drop (2), and
            % the forward edge demands {out.dx,out.f} on the subfunction, whose
            % unread out.dx_location drops (1) -> 3 lines total.
            [out, info] = adigatorSlimDerivFile(interprocFile(), {'f','dx'});
            tc.verifyTrue(info.sliced);
            tc.verifyEqual(info.dropped, 3);
            % metadata gone in BOTH functions
            tc.verifyFalse(any(contains(out,'dx_location')));
            tc.verifyFalse(any(contains(out,'dx_size')));
            tc.verifyFalse(any(contains(out,'Index1')));
            % the call and both functions' demanded value chains survive
            tc.verifyTrue(any(contains(out,'cadaoutput1 = ADiGator_sub(cadainput1)')));
            tc.verifyTrue(any(contains(out,'cadainput1.dx = gx.dx')));
            tc.verifyTrue(any(contains(out,'y.dx = cada1d1;')));
            tc.verifyTrue(any(contains(out,'y.f = cada1f1;')));
            tc.verifyTrue(any(contains(out,'out.dx = cada1sd1;')));
            tc.verifyTrue(any(contains(out,'out.f = cada1s1;')));
            % skeleton preserved: both headers, both markers, the loader
            tc.verifyTrue(any(contains(out,'function y = mf_ADiGatorJac(gx)')));
            tc.verifyTrue(any(contains(out,'function out = ADiGator_sub(z)')));
            tc.verifyTrue(any(contains(out,'function ADiGator_LoadData()')));
            tc.verifyEqual(nnz(contains(out,'ADiGator Start Derivative Computations')), 2);
        end

        function slicesSubEvenWhenMainDemandsEverything(tc)
            % out.dx_location is sub-internal: no caller ever reads
            % cadaoutput1.dx_location, so it is dead regardless of what the main
            % wrapper demands - the interprocedural payoff. Demanding ALL of
            % main's fields still slices the subfunction.
            [out, info] = adigatorSlimDerivFile(interprocFile(), ...
                {'f','dx','dx_location','dx_size'});
            tc.verifyTrue(info.sliced);
            tc.verifyEqual(info.dropped, 1);
            % main keeps its (now-demanded) metadata ...
            tc.verifyTrue(any(contains(out,'y.dx_location =')));
            tc.verifyTrue(any(contains(out,'y.dx_size =')));
            % ... but the subfunction's unread out.dx_location is gone
            tc.verifyFalse(any(contains(out,'out.dx_location')));
        end

        function delegatesForSingleFunctionFile(tc)
            % no ADiGator_* subfunction -> identical to the intra-function path
            f = singleFunctionFile();
            [a, ia] = adigatorSlimDerivFile(f, {'f','dx'});
            [b, ib] = adigatorSlimDerivBody(f, {'f','dx'});
            tc.verifyEqual(a, b);
            tc.verifyEqual(ia.sliced, ib.sliced);
            tc.verifyEqual(ia.dropped, ib.dropped);
            tc.verifyTrue(ia.sliced);
        end

        function bailsOnNoDemandedFields(tc)
            [out, info] = adigatorSlimDerivFile(interprocFile(), {});
            tc.verifyFalse(info.sliced);
            tc.verifyEqual(info.reason, 'no demanded fields');
            tc.verifyEqual(out, string(interprocFile()));
        end

        function bailsOnRolledLoopInMultiSubfunction(tc)
            % a rolled for...end whose interior the top-level scans cannot see:
            % the interprocedural slicer must bail the whole file unchanged
            [out, info] = adigatorSlimDerivFile(interprocRolledFile(), {'f','dx'});
            tc.verifyFalse(info.sliced);
            tc.verifyTrue(contains(info.reason,'rolled loop'));
            tc.verifyEqual(out, string(interprocRolledFile()));
        end
    end
end

% ---------------------------- fixtures --------------------------------- %
function f = interprocFile()
% a minimal multi-subfunction _ADiGatorJac: main calls ADiGator_sub, reads its
% .f/.dx, assembles y.{dx,dx_location,dx_size,f}; the subfunction produces
% out.{dx,dx_location,f}. Demanded {f,dx} must drop the *_location/_size
% metadata in BOTH functions.
f = [ ...
    "function y = mf_ADiGatorJac(gx)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "if isempty(ADiGator_mf_ADiGatorJac); ADiGator_LoadData(); end"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.mf_ADiGatorJac.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cadainput1.dx = gx.dx; cadainput1.f = gx.f;"; ...
    "cadaoutput1 = ADiGator_sub(cadainput1);"; ...
    "cada1f1 = cadaoutput1.f;"; ...
    "cada1d1 = cadaoutput1.dx;"; ...
    "y.dx = cada1d1;"; ...
    "y.dx_location = Gator1Data.Index1;"; ...
    "y.dx_size = [2 1];"; ...
    "y.f = cada1f1;"; ...
    "end"; ...
    "function out = ADiGator_sub(z)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.ADiGator_sub.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cada1s1 = z.f.^2;"; ...
    "cada1sd1 = 2.*z.f.*z.dx;"; ...
    "out.dx = cada1sd1;"; ...
    "out.dx_location = Gator1Data.Index1;"; ...
    "out.f = cada1s1;"; ...
    "end"; ...
    "function ADiGator_LoadData()"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "load('mf_ADiGatorJac.mat')"; ...
    "end"];
end

function f = interprocRolledFile()
% interprocFile with the main .dx assembled by a rolled for...end loop: the
% multi-subfunction interprocedural slicer must conservatively bail.
f = [ ...
    "function y = mf_ADiGatorJac(gx)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "if isempty(ADiGator_mf_ADiGatorJac); ADiGator_LoadData(); end"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.mf_ADiGatorJac.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cadainput1.dx = gx.dx; cadainput1.f = gx.f;"; ...
    "cadaoutput1 = ADiGator_sub(cadainput1);"; ...
    "cada1d1 = zeros(2,1);"; ...
    "for cadaforcount1 = 1:2"; ...
    "  cada1d1(cadaforcount1) = cadaoutput1.dx(cadaforcount1);"; ...
    "end"; ...
    "y.dx = cada1d1;"; ...
    "y.f = cadaoutput1.f;"; ...
    "end"; ...
    "function out = ADiGator_sub(z)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.ADiGator_sub.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cada1s1 = z.f.^2;"; ...
    "cada1sd1 = 2.*z.f.*z.dx;"; ...
    "out.dx = cada1sd1;"; ...
    "out.f = cada1s1;"; ...
    "end"; ...
    "function ADiGator_LoadData()"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "load('mf_ADiGatorJac.mat')"; ...
    "end"];
end

function f = singleFunctionFile()
% a single-derivative-function file (no ADiGator_* subfunction): demand {f,dx}
% drops the .dx_location/.dx_size metadata via the delegated intra-function path
f = [ ...
    "function y = mf_ADiGatorJac(gator_x)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "if isempty(ADiGator_mf_ADiGatorJac); ADiGator_LoadData(); end"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.mf_ADiGatorJac.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cada1f1 = gator_x.f.^2;"; ...
    "cada1d1 = 2.*gator_x.f.*gator_x.dx;"; ...
    "y.dx = cada1d1;"; ...
    "y.dx_location = Gator1Data.Index1;"; ...
    "y.dx_size = [2 1];"; ...
    "y.f = cada1f1;"; ...
    "end"; ...
    "function ADiGator_LoadData()"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "load('mf_ADiGatorJac.mat')"; ...
    "end"];
end
