classdef USlimDerivFileTest < matlab.unittest.TestCase
    % USlimDerivFileTest  Unit tests for the interprocedural field-slice
    % (issue #44 item 1; ADR-0009): adigatorSlimDerivFile splits a multi-
    % subfunction generated _ADiGator* file into its per-function blocks, runs
    % a forward worklist that pushes the result-struct fields a caller reads at
    % a kept call site as demand on the callee, field-slices each block under
    % the per-function closure gate, and reassembles - dropping dead value
    % chains and unread output fields in EVERY function. For a single-derivative
    % -function file it delegates to adigatorSlimDerivBody (proven path). Text-
    % in / text-out on hand-written snippets; no toolbox, no file I/O.

    methods (TestClassSetup)
        function addPaths(tc)
            import matlab.unittest.fixtures.PathFixture
            testDir = fileparts(mfilename('fullpath'));
            root = fileparts(fileparts(testDir));
            tc.applyFixture(PathFixture(fullfile(root,'util')));
        end
    end

    methods (Test)
        function slicesAcrossTheCall(tc)
            % main demands {f,dx}: its own .dx_location/.dx_size drop (2), and
            % the forward edge demands {out.dx,out.f} on the subfunction, whose
            % unread out.dx_location drops (1) -> 3 lines total.
            [out, info] = adigatorSlimDerivFile(interprocFile(), {'f','dx'});
            tc.verifyTrue(info.sliced);
            tc.verifyEqual(info.dropped, 3);
            % metadata gone in BOTH functions
            tc.verifyFalse(any(contains(out,'dx_location')));
            tc.verifyFalse(any(contains(out,'dx_size')));
            tc.verifyFalse(any(contains(out,'Index1')));
            % the call and both functions' demanded value chains survive
            tc.verifyTrue(any(contains(out,'cadaoutput1 = ADiGator_sub(cadainput1)')));
            tc.verifyTrue(any(contains(out,'cadainput1.dx = gx.dx')));
            tc.verifyTrue(any(contains(out,'y.dx = cada1d1;')));
            tc.verifyTrue(any(contains(out,'y.f = cada1f1;')));
            tc.verifyTrue(any(contains(out,'out.dx = cada1sd1;')));
            tc.verifyTrue(any(contains(out,'out.f = cada1s1;')));
            % skeleton preserved: both headers, both markers, the loader
            tc.verifyTrue(any(contains(out,'function y = mf_ADiGatorJac(gx)')));
            tc.verifyTrue(any(contains(out,'function out = ADiGator_sub(z)')));
            tc.verifyTrue(any(contains(out,'function ADiGator_LoadData()')));
            tc.verifyEqual(nnz(contains(out,'ADiGator Start Derivative Computations')), 2);
        end

        function slicesSubEvenWhenMainDemandsEverything(tc)
            % out.dx_location is sub-internal: no caller ever reads
            % cadaoutput1.dx_location, so it is dead regardless of what the main
            % wrapper demands - the interprocedural payoff. Demanding ALL of
            % main's fields still slices the subfunction.
            [out, info] = adigatorSlimDerivFile(interprocFile(), ...
                {'f','dx','dx_location','dx_size'});
            tc.verifyTrue(info.sliced);
            tc.verifyEqual(info.dropped, 1);
            % main keeps its (now-demanded) metadata ...
            tc.verifyTrue(any(contains(out,'y.dx_location =')));
            tc.verifyTrue(any(contains(out,'y.dx_size =')));
            % ... but the subfunction's unread out.dx_location is gone
            tc.verifyFalse(any(contains(out,'out.dx_location')));
        end

        function delegatesForSingleFunctionFile(tc)
            % no ADiGator_* subfunction -> identical to the intra-function path
            f = singleFunctionFile();
            [a, ia] = adigatorSlimDerivFile(f, {'f','dx'});
            [b, ib] = adigatorSlimDerivBody(f, {'f','dx'});
            tc.verifyEqual(a, b);
            tc.verifyEqual(ia.sliced, ib.sliced);
            tc.verifyEqual(ia.dropped, ib.dropped);
            tc.verifyTrue(ia.sliced);
        end

        function bailsOnNoDemandedFields(tc)
            [out, info] = adigatorSlimDerivFile(interprocFile(), {});
            tc.verifyFalse(info.sliced);
            tc.verifyEqual(info.reason, 'no demanded fields');
            tc.verifyEqual(out, string(interprocFile()));
        end

        function slicesRolledLoopReadingCalleeResult(tc)
            % R10(a): a rolled for...end that READS a callee result field
            % (cadaoutput1.dx) INSIDE the loop, with the call itself at top
            % level. The block-aware result-field scan must see the in-loop read
            % so the callee keeps out.dx; the unread *_location/_size drop in
            % both functions (3), the loop is preserved, and out.dx survives.
            [out, info] = adigatorSlimDerivFile(interprocRolledReadFile(), {'f','dx'});
            tc.verifyTrue(info.sliced);
            tc.verifyEqual(info.dropped, 3);
            tc.verifyFalse(any(contains(out,'dx_location')));
            tc.verifyFalse(any(contains(out,'dx_size')));
            % the rolled loop and the demanded callee chain survive
            tc.verifyTrue(any(contains(out,'for cadaforcount1 = 1:2')));
            tc.verifyTrue(any(contains(out,'cadaoutput1 = ADiGator_sub(cadainput1)')));
            tc.verifyTrue(any(contains(out,'out.dx = cada1sd1;')));  % NOT under-demanded
            tc.verifyTrue(any(contains(out,'out.f = cada1s1;')));
            tc.verifyEqual(nnz(contains(out,'ADiGator Start Derivative Computations')), 2);
        end

        function slicesRolledLoopWithInnerCall(tc)
            % R10(a): the subfunction CALL itself is nested in the rolled loop
            % (cadaoutput1 = ADiGator_sub(...) inside for...end), and both
            % result fields are read in the loop. The block-aware call-site and
            % result-field scans must find the in-loop call and reads, propagate
            % {dx,f} to the callee, and still drop only the unread metadata (3).
            [out, info] = adigatorSlimDerivFile(interprocRolledCallFile(), {'f','dx'});
            tc.verifyTrue(info.sliced);
            tc.verifyEqual(info.dropped, 3);
            tc.verifyFalse(any(contains(out,'dx_location')));
            tc.verifyFalse(any(contains(out,'dx_size')));
            tc.verifyTrue(any(contains(out,'for cadaforcount1 = 1:2')));
            tc.verifyTrue(any(contains(out,'cadaoutput1 = ADiGator_sub(cadainput1)')));
            tc.verifyTrue(any(contains(out,'out.dx = cada1sd1;')));
            tc.verifyTrue(any(contains(out,'out.f = cada1s1;')));
            tc.verifyEqual(nnz(contains(out,'ADiGator Start Derivative Computations')), 2);
        end

        function bailsOnSubscriptedInnerCallResult(tc)
            % conservative guard retained: a call nested in a loop whose result
            % is NOT a plain whole-struct assignment (here a subscripted LHS)
            % cannot have its read fields tracked, so the whole file bails
            % unchanged - exactly as a malformed top-level call would.
            [out, info] = adigatorSlimDerivFile(interprocRolledBadCallFile(), {'f','dx'});
            tc.verifyFalse(info.sliced);
            tc.verifyTrue(contains(info.reason,'call site'));
            tc.verifyEqual(out, string(interprocRolledBadCallFile()));
        end
    end
end

% ---------------------------- fixtures --------------------------------- %
function f = interprocFile()
% a minimal multi-subfunction _ADiGatorJac: main calls ADiGator_sub, reads its
% .f/.dx, assembles y.{dx,dx_location,dx_size,f}; the subfunction produces
% out.{dx,dx_location,f}. Demanded {f,dx} must drop the *_location/_size
% metadata in BOTH functions.
f = [ ...
    "function y = mf_ADiGatorJac(gx)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "if isempty(ADiGator_mf_ADiGatorJac); ADiGator_LoadData(); end"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.mf_ADiGatorJac.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cadainput1.dx = gx.dx; cadainput1.f = gx.f;"; ...
    "cadaoutput1 = ADiGator_sub(cadainput1);"; ...
    "cada1f1 = cadaoutput1.f;"; ...
    "cada1d1 = cadaoutput1.dx;"; ...
    "y.dx = cada1d1;"; ...
    "y.dx_location = Gator1Data.Index1;"; ...
    "y.dx_size = [2 1];"; ...
    "y.f = cada1f1;"; ...
    "end"; ...
    "function out = ADiGator_sub(z)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.ADiGator_sub.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cada1s1 = z.f.^2;"; ...
    "cada1sd1 = 2.*z.f.*z.dx;"; ...
    "out.dx = cada1sd1;"; ...
    "out.dx_location = Gator1Data.Index1;"; ...
    "out.f = cada1s1;"; ...
    "end"; ...
    "function ADiGator_LoadData()"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "load('mf_ADiGatorJac.mat')"; ...
    "end"];
end

function f = interprocRolledReadFile()
% Multi-subfunction file whose main READS a callee result field inside a rolled
% loop (cadaoutput1.dx in the for...end), with the call at top level. The block-
% aware result-field scan must demand out.dx on the callee so it is not dropped.
% Dead *_location/_size in both functions (3) drop; the loop is preserved.
f = [ ...
    "function y = mf_ADiGatorJac(gx)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "if isempty(ADiGator_mf_ADiGatorJac); ADiGator_LoadData(); end"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.mf_ADiGatorJac.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cadainput1.dx = gx.dx; cadainput1.f = gx.f;"; ...
    "cadaoutput1 = ADiGator_sub(cadainput1);"; ...
    "cada1d1 = zeros(2,1);"; ...
    "for cadaforcount1 = 1:2"; ...
    "  cada1d1(cadaforcount1) = cadaoutput1.dx(cadaforcount1);"; ...
    "end"; ...
    "y.dx = cada1d1;"; ...
    "y.dx_location = Gator1Data.Index1;"; ...
    "y.dx_size = [2 1];"; ...
    "y.f = cadaoutput1.f;"; ...
    "end"; ...
    "function out = ADiGator_sub(z)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.ADiGator_sub.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cada1s1 = z.f.^2;"; ...
    "cada1sd1 = 2.*z.f.*z.dx;"; ...
    "out.dx = cada1sd1;"; ...
    "out.dx_location = Gator1Data.Index1;"; ...
    "out.f = cada1s1;"; ...
    "end"; ...
    "function ADiGator_LoadData()"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "load('mf_ADiGatorJac.mat')"; ...
    "end"];
end

function f = interprocRolledCallFile()
% Multi-subfunction file whose subfunction CALL is itself nested in the rolled
% loop (cadaoutput1 = ADiGator_sub(...) inside for...end), with both result
% fields read in the loop. The block-aware call-site + result-field scans must
% find the in-loop call and reads and demand {dx,f} on the callee; only the
% unread *_location/_size drop (3).
f = [ ...
    "function y = mf_ADiGatorJac(gx)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "if isempty(ADiGator_mf_ADiGatorJac); ADiGator_LoadData(); end"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.mf_ADiGatorJac.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cada1d1 = zeros(2,1);"; ...
    "for cadaforcount1 = 1:2"; ...
    "  cadainput1.dx = gx.dx; cadainput1.f = gx.f;"; ...
    "  cadaoutput1 = ADiGator_sub(cadainput1);"; ...
    "  cada1f1 = cadaoutput1.f;"; ...
    "  cada1d1(cadaforcount1) = cadaoutput1.dx(cadaforcount1);"; ...
    "end"; ...
    "y.dx = cada1d1;"; ...
    "y.dx_location = Gator1Data.Index1;"; ...
    "y.dx_size = [2 1];"; ...
    "y.f = gx.f;"; ...
    "end"; ...
    "function out = ADiGator_sub(z)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.ADiGator_sub.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cada1s1 = z.f.^2;"; ...
    "cada1sd1 = 2.*z.f.*z.dx;"; ...
    "out.dx = cada1sd1;"; ...
    "out.dx_location = Gator1Data.Index1;"; ...
    "out.f = cada1s1;"; ...
    "end"; ...
    "function ADiGator_LoadData()"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "load('mf_ADiGatorJac.mat')"; ...
    "end"];
end

function f = interprocRolledBadCallFile()
% interprocRolledCallFile but the in-loop call assigns a SUBSCRIPTED result
% (cadaoutcell(cadaforcount1) = ADiGator_sub(...)) rather than a whole struct:
% the call-site scan cannot track its read fields, so the whole file bails.
f = [ ...
    "function y = mf_ADiGatorJac(gx)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "if isempty(ADiGator_mf_ADiGatorJac); ADiGator_LoadData(); end"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.mf_ADiGatorJac.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cada1d1 = zeros(2,1);"; ...
    "for cadaforcount1 = 1:2"; ...
    "  cadainput1.dx = gx.dx; cadainput1.f = gx.f;"; ...
    "  cadaoutcell(cadaforcount1) = ADiGator_sub(cadainput1);"; ...
    "  cada1d1(cadaforcount1) = cadaoutcell(cadaforcount1).dx;"; ...
    "end"; ...
    "y.dx = cada1d1;"; ...
    "y.f = gx.f;"; ...
    "end"; ...
    "function out = ADiGator_sub(z)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.ADiGator_sub.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cada1s1 = z.f.^2;"; ...
    "cada1sd1 = 2.*z.f.*z.dx;"; ...
    "out.dx = cada1sd1;"; ...
    "out.f = cada1s1;"; ...
    "end"; ...
    "function ADiGator_LoadData()"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "load('mf_ADiGatorJac.mat')"; ...
    "end"];
end

function f = singleFunctionFile()
% a single-derivative-function file (no ADiGator_* subfunction): demand {f,dx}
% drops the .dx_location/.dx_size metadata via the delegated intra-function path
f = [ ...
    "function y = mf_ADiGatorJac(gator_x)"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "if isempty(ADiGator_mf_ADiGatorJac); ADiGator_LoadData(); end"; ...
    "Gator1Data = ADiGator_mf_ADiGatorJac.mf_ADiGatorJac.Gator1Data;"; ...
    "% ADiGator Start Derivative Computations"; ...
    "cada1f1 = gator_x.f.^2;"; ...
    "cada1d1 = 2.*gator_x.f.*gator_x.dx;"; ...
    "y.dx = cada1d1;"; ...
    "y.dx_location = Gator1Data.Index1;"; ...
    "y.dx_size = [2 1];"; ...
    "y.f = cada1f1;"; ...
    "end"; ...
    "function ADiGator_LoadData()"; ...
    "global ADiGator_mf_ADiGatorJac"; ...
    "load('mf_ADiGatorJac.mat')"; ...
    "end"];
end
