function [Grd, Fun] = lse_cost_RGrd(x,w)
% lse_cost_RGrd - reverse-mode (adjoint) gradient of 'lse_cost'
% Returns [Grd, Fun]: the 4 x 1 gradient w.r.t. x, then the scalar value (C-6 order).
% Generated by adigatorGenRevGradFile (roadmap R4, issue #6/#11 companion)
% which is passed as a plain 4 x 1 numeric array.
% ADiGator Start Derivative Computations
% BEGIN-rgrd-core
% ----------------- forward (function value) sweep ----------------- %
cada1f1 = w.*x;
cada1f2 = exp(cada1f1);
cada1f3 = sum(cada1f2);
y.f = log(cada1f3);
% -------------------------- reverse sweep -------------------------- %
cadaRGb4 = 1;
cadaRGb3 = zeros(1,1);
cadaRGb3 = cadaRGb3 + cadaRGb4./cada1f3;
cadaRGb2 = zeros(4,1);
cadaRGb2 = cadaRGb2 + cadaRGb3;
cadaRGb1 = zeros(4,1);
cadaRGb1 = cadaRGb1 + cadaRGb2.*cada1f2;
cadaRGbx = zeros(4,1);
cadaRGbx = cadaRGbx + cadaRGb1.*w;
Fun = y.f;
Grd = cadaRGbx(:);
% END-rgrd-core
end
